# Generated by Django 3.2.4 on 2021-06-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.company'),
        ),
    ]
