# Generated by Django 3.2.4 on 2021-06-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_car_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcolor',
            old_name='name',
            new_name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carcolor'),
        ),
    ]
