# Generated by Django 3.2.4 on 2021-06-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20210611_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcolor',
            old_name='color',
            new_name='name',
        ),
    ]
