# Generated by Django 3.2.4 on 2021-06-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_rename_color_carcolor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.cardate'),
        ),
    ]
