# Generated by Django 3.2.4 on 2021-06-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20210611_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardate',
            name='name',
            field=models.IntegerField(default=1950),
        ),
    ]
