# Generated by Django 3.2.4 on 2021-06-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20210611_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model']},
        ),
    ]
